name: tests
on:
  workflow_call:
    inputs:
      default_modifier:
        type: string
        default: ""
    secrets:
      gcp_identity_provider:
        required: true
      gcp_service_account:
        required: true
      gcp_project:
        required: true
      gcp_region:
        required: true
      gcp_zone:
        required: true
      aws_role:
        required: true
      aws_session:
        required: true
      aws_region:
        required: true
      az_client_id:
        required: true
      az_tenant_id:
        required: true
      az_subscription_id:
        required: true
jobs:
  platform_tests:
    name: platform test
    env:
      gcp_project: ${{ secrets.gcp_project }}
      gcp_region: ${{ secrets.gcp_region }}
      gcp_zone: ${{ secrets.gcp_zone }}
      aws_region: ${{ secrets.aws_region }}
      azure_subscription_id: ${{ secrets.az_subscription_id }}
      AZURE_CONFIG_DIR: /tmp/azure_config_dir
    runs-on: ec2-gardenlinux-amd64
    permissions:
      id-token: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        architecture: [ amd64, arm64 ]
        target: [ gcp, aws, azure ]
        modifier: [ "${{ inputs.default_modifier }}" ]
        exclude:
          - architecture: arm64
            target: gcp
          - architecture: arm64
            target: azure
    steps:
    - uses: actions/checkout@v3

    - name: login to ghcr.io
      run: echo "${{ secrets.GITHUB_TOKEN }}" | sudo podman login ghcr.io -u $ --password-stdin

    - name: pull container image
      run: |
        sudo podman pull "ghcr.io/gardenlinux/gardenlinux/integration-test:$GITHUB_SHA"
        sudo podman tag "ghcr.io/gardenlinux/gardenlinux/integration-test:$GITHUB_SHA" ghcr.io/gardenlinux/gardenlinux/integration-test:today

    - uses: actions/download-artifact@v2
      with:
        name: build-${{ matrix.architecture }}-${{ matrix.target }}${{ matrix.modifier }}
        path: /tmp/gardenlinux-build-artifacts

    - if: ${{ matrix.target }} == 'gcp'
      id: 'auth_gcp'
      name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: ${{ secrets.gcp_identity_provider }}
        service_account: ${{ secrets.gcp_service_account }}

    - if: ${{ matrix.target }} == 'aws'
      id: 'auth_aws'
      name: 'Authenticate to AWS'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.aws_role }}
        role-session-name: ${{ secrets.aws_session }}
        aws-region: ${{ secrets.aws_region }}

    - name: patch MSAL
      run: echo "LS0tIGEvYXBwbGljYXRpb24ucHkJMjAyMi0xMC0xOSAxNDoxOToxMi42NjUzMTMyNDUgKzAwMDAKKysrIGIvYXBwbGljYXRpb24ucHkJMjAyMi0xMC0xOSAxNDoxOTo0OS4yNjEyNTA3NDEgKzAwMDAKQEAgLTE3NCw2ICsxNzQsNyBAQAogICAgICAgICAgICAgICAgICMgd2hlbiB3ZSB3b3VsZCBldmVudHVhbGx5IHdhbnQgdG8gYWRkIHRoaXMgZmVhdHVyZSB0byBQQ0EgaW4gZnV0dXJlLgogICAgICAgICAgICAgZXhjbHVkZV9zY29wZXM9Tm9uZSwKICAgICAgICAgICAgIGh0dHBfY2FjaGU9Tm9uZSwKKyAgICAgICAgICAgIGFsbG93X2Jyb2tlcj1Ob25lLAogICAgICAgICAgICAgKToKICAgICAgICAgIiIiQ3JlYXRlIGFuIGluc3RhbmNlIG9mIGFwcGxpY2F0aW9uLgogCg==" | base64 -d | sudo patch /usr/lib/python3/dist-packages/msal/application.py

    - if: ${{ matrix.target }} == 'azure'
      id: 'auth_azure'
      name: 'Authenticate to Azure'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.az_client_id }}
        tenant-id: ${{ secrets.az_tenant_id }}
        subscription-id: ${{ secrets.az_subscription_id }}

    - name: start platform test for ${{ matrix.target }}
      run: .github/workflows/${{ matrix.target }}_tests.sh --arch "${{ matrix.architecture }}" "${{ matrix.target }}${{ matrix.modifier }}-${{ matrix.architecture }}-*.tar.gz"
